"""MediaProvider interface + result type.

All adapters must:
  - Be safe to call from a Celery worker (sync, retryable).
  - Persist generated bytes to MinIO via core.storage.
  - Return a `MediaResult` referring to the stored S3 key, NOT bytes.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Literal

Kind = Literal["image", "video", "voiceover", "notebook_audio"]


@dataclass
class MediaResult:
    s3_key: str
    mime: str
    kind: Kind
    provider: str
    prompt: str
    width: int | None = None
    height: int | None = None
    duration_s: float | None = None


class MediaProvider(ABC):
    name: str = "base"
    enabled: bool = True

    @abstractmethod
    def generate_image(self, *, tenant_id: str, prompt: str, **kwargs) -> MediaResult: ...

    def generate_video(self, *, tenant_id: str, prompt: str, **kwargs) -> MediaResult:
        raise NotImplementedError

    def generate_voiceover(self, *, tenant_id: str, text: str, **kwargs) -> MediaResult:
        raise NotImplementedError

    def generate_notebook_audio(self, *, tenant_id: str, sources: list[str], **kwargs) -> MediaResult:
        raise NotImplementedError
